### ISSUE TITLE
Setting partition field using property in topic's value part

### ISSUE THREAD

**Issue by rjdp** [getindata/kafka-connect-iceberg-sink#18]
How can we use partition timestamp field other than message ingest time, I want to use mongo object Id , which I am able to convert using a custom udf and create a stream on it.

suppose this is my stream backed by topic "k1"

```
select   FORMAT_TIMESTAMP(FROM_UNIXTIME(objectidtoepoch(EXTRACTJSONFIELD(payload, '$.nestes.fullDocument._id["$oid"]'))), 'yyyy-MM-dd HH:mm:ss.SSS') as ts, EXTRACTJSONFIELD(payload, '$.nestes.fullDocument.first_name') as first_name from data_compliance_stream;
```

I would like to use the `ts` field for partitioning

**Comment by gliter** [comment]
This connector consumes Debezium events, they have a transaction timestamp that is used by this connector for partitioning key, with current implementation there is no possiblity to configure which field is used for partitioning but you could write Kafka Connect transformation to put value of that field in the `ts` field.

https://github.com/getindata/kafka-connect-iceberg-sink#iceberg-partitioning-support

**Comment by gliter** [comment]
@johanhenriksson I dont recently have time to do some implementation here but I would be happy to do the review.

**Comment by gliter** [comment]
@johanhenriksson It should be in the first format you presented, the reason why in source it looks like that it is that before Sink there is an unwrap transformation:

```
transforms: unwrap
transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
transforms.unwrap.add.fields: op,table,source.ts_ms,db
```

**Comment by gliter** [comment]
To be more specific it should be
```
{
  "source" : {
    "ts_ms": 123
  }
}
```
