### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration

### ISSUE THREAD

**Issue by junsik-gsitm** [getindata/kafka-connect-iceberg-sink#48]
java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration at com.getindata.kafka.connect.iceberg.sink.IcebergCatalogFactory.create(IcebergCatalogFactory.java:11) at com.getindata.kafka.connect.iceberg.sink.IcebergSinkTask.start(IcebergSinkTask.java:29) at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:315) at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202) at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:259) at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by heman026** [comment]
@junsik-gsitm  Did you solve the issue. I am also getting the same error
